### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Pharap**
This fixes all outstanding warnings.

(Aside from the EEPROM one, but that's Arduino's fault and can't be helped.)

### CODE REVIEW

**Review by TheProgrammer163 — APPROVED** [review]
I think I was planning on simply never calling this function with entities that are of type "none". Or maybe I was planning on using some sprite that is simply an "X" to say that it is an invalid sprite, not sure.

Still, since this function is currently not beint used anywhere I don't see a reason to keep it.

**Review by TheProgrammer163 — APPROVED** [review]
I didn't know that, thank you!

**Review by TheProgrammer163 — APPROVED** [review]
Definitely looks like an oversight, thanks!

**Comment by Pharap** [comment]
For future reference...

> I think I was planning on simply never calling this function with entities that are of type "none". Or maybe I was planning on using some sprite that is simply an "X" to say that it is an invalid sprite, not sure.

It can always be reinstated later - as long as you have the git history you can peek back in time to see the code that was removed.
Though to get it working you'd need to change the return type to `const uint8_t *` and make sure the `switch` had a `default` that returned either a blank/placeholder sprite or `nullptr`, depending on how brave you're feeling.

> and using 'static' specifies internal language which is incompatible with external linkage,

This should say 'internal linkage', not 'internal language'.
I don't use a phone for typing, but I still get tripped up by my brain's own autocorrect. `:P`

**Pull request merged**
